config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'notes/search', action: :search, controller: 'notes'
  post 'notes/:id/likes', to: 'notes#like', as: 'note_like'
  # resources :comments
  devise_for :users
  resources :notes
  root "notes#index"
  resources :notes do 
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50 }
  has_one_attached :photo
  has_rich_text :content
  acts_as_taggable_on :tags
  acts_as_commentable
  acts_as_votable
  has_many :articles, dependent: :destroy
end

app/controllers/notes_controller.rb
# require 'rubygems'
# require 'mechanize'

class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :like]

  # GET /notes or /notes.json
  def index
    # @notes = Note.all
    if params[:title].nil?
      @notes = Note.all
    else
      puts params[:title]
      @notes = Note.where(title: params[:title])
    end
  end

  # GET /notes/1 or /notes/1.json
  def show
    @note.increment!(:view_count)
  end

  # GET /notes/newo
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)
    if @note.article_link.present?
      @article = crawl(@note.article_link, @note)
      @note.save
      @article.note = @note
      @article.save
    end


    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @notes = Note.all
  end

  def like
    set_note
    if user_signed_in?
      if @current_user.voted_for? @note
        @note.unliked_by @current_user
      else
        @note.liked_by @current_user
      end
    end
    redirect_to note_path(@note)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :body, :photo, :content, :tag_list, :article_link)
    end

    def crawl(article_link, note)
      agent = Mechanize.new
      page = agent.get(article_link)
      
      url = article_link
      title = page.search("//meta[@property='og:title']/@content").text
      summary = page.search("//meta[@property='og:description']/@content").text
      publishedAt = page.search("//meta[@property='og:regDate']/@content").text
      imageSrc = page.search("//meta[@property='og:image']/@content").text
      press = ''
      reporter = ''
      # press = page.search("//em[@class='info_cp']/a/@href").text
      # reporter = page.search("//span[@class='info_view']/span[@class='txt_info']").first.text

      article = Article.new(:url=>url, :title=>title, :summary=>summary, :press=>press, :publishedAt=>publishedAt, :reporter=>reporter, :imageSrc=>imageSrc)

      return article
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, '제목' %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :article_link, '기사 링크' %>
    <%= form.text_field :article_link, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :content, '본문' %>
    <%= form.rich_text_area :content, class:"form-control", rows: 3 %>
  </div>

  <div class="form-group">
    <%= form.label :photo , '사진 업로드'%>
    <%= form.file_field :photo, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.label :tag_list, '태그' %>
    <%= form.text_field :tag_list, value: @note.tag_list.join(', '), class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "작성하기", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<div class="row pb-5">
  <div class="col">
    <a class="btn btn-primary btn-sm" href="<%= new_note_path %>">새 노트</a>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="row note-list-container">
      <% @notes.each do |note| %>
        <div class="col-12">
          <a href="<%= note_path(note) %>">
          <div class="card note">
            <div class="card-body">
              <%= note.title %>
              <span class="note-tags">
                <% note.tags.each do |tag| %>
                  <span>#<%= tag.name %></span>
                <% end %>
              </span>
            </div>
          </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/new.html.erb
<div class="row">
  <div class="col">
    <h2>새 노트</h2>
  </div>
</div>

<div class="row">
  <div class="col mt-3">
    <%= render 'form', note: @note %>
  </div>
</div>


<%= link_to '뒤로', notes_path %>

app/views/notes/show.html.erb
<div class="row">
  <div class="col">
    <% if notice.present? %>
      <div id="notice" class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col">
    <h2>
      <%= @note.title %>
    </h2>
    <p style="text-align: right;">
      <span><strong>조회수:</strong></span>
      <span>
        <%= @note.view_count %>
      </span>
    </p>
  </div>
</div>

<div class="row">
    <% @note.articles.each do |article| %>
    <div class="col">
      <div class="card note-article-container">
        <% if article.imageSrc.present? %>
          <img src="<%= article.imageSrc %>" class="card-img-top" alt="기사 사진">
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><%= article.summary %></p>
          <p class="card-text"><%= article.publishedAt %></p>
          <a href="<%= article.url %>" class="btn btn-outline-primary btn-sm">기사 보기</a>
        </div>
      </div>
    </div>
    <% end %>
</div>

<div class="row">
  <div class="col note-content-container py-3">
    <%= @note.content %>
  </div>
</div>


<div class="row">
  <div class="col">
    <strong>태그</strong>
    <% @note.tags.each do |tag| %>
      <span><strong>#</strong><%= tag.name %></span>
    <% end %>
  </div>
</div>


<div class="row">
  <div class="col">
    <p>
      <% if @note.photo.attached? %>
        <%= image_tag(@note.photo.variant(resize_to_limit: [300, 300]), :alt=> "Note Photo") %>
      <% end %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col">
    <%= button_to "좋아요", note_like_path(@note), class:"btn btn-primary btn-sm" %>
    <span>좋아요 수</span>
    <span><%= @note.get_likes.size %></span>
  </div>
</div>

<div class="row py-3">
  <div class="col">
    <%= button_to "수정", edit_note_path(@note), class:"btn btn-primary btn-sm" %>
    <%= link_to '삭제', @note, method: :delete, data: { confirm: 'Are you sure?' } %> | 
    <%= link_to '목록', notes_path %>
  </div>
</div>

<hr>

<div class="row">
  <div class="col">
    <h4>댓글</h4>
    <% @note.comment_threads.each do |comment| %>
      <div class="row border">
        <div class="col-12">
          <p class=""><%= comment.user.email %></p>
          <div class="row">
            <div class="col-10">
              <p><%= comment.body %></p>
            </div>
            <div class="col-2" style="text-align: right;">
              <span><%= link_to '수정', edit_note_comment_path(@note, comment) %></span>
              <span><%= link_to '삭제', note_comment_path(@note, comment), method: :delete, data: { confirm: 'Are you sure?' } %></span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<hr>

<div class="row">
  <div class="col">
    <p>댓글 작성</p>
    <%= form_with model: [ @note, @note.comment_threads.build ] do |form| %>
      <p><%= form.text_area :body %></p>
      <p><%= form.submit %></p>
    <% end %>
  </div>
</div>